export const books = [
  {
    id: 1,
    title: "Love Deception",
    img: "/images/book-3.jpg",
    author: "Elena Armas",
    genre: "Mystery",
    desc: "THIS BOOK HAS NOW LIVED TO SEE nearly one hundred printings in English—in addition to having been published in twenty-one other languages. And the English editions alone have sold more than three million copies These are the dry facts.",
    published: "Jan 2, 2004",
  },
  {
    id: 2,
    title: "Men's Search For Meaning",
    genre: "Adventure",
    img: "/images/book-4.jpg",
    author: "Victor Franki",
    desc: "THIS BOOK HAS NOW LIVED TO SEE nearly one hundred printings in English—in addition to having been published in twenty-one other languages. And the English editions alone have sold more than three million copies. ",
    published: "Feb 2, 2004",
  },

  {
    id: 3,
    title: "Home Business HandBook",
    author: "JunkyBooks",
    genre: "Politics",
    img: "/images/book-11.jpg",
    published: "Jan27 2007",
    desc: "You won’t be amazing at being a home business owner unless and until you condition your brain for entering a business and then making the most of it. And so, how do you accomplish that effectively? Here are a few awesome hints on how you're able to become that amazing home business owner.",
  },
  {
    id: 4,
    genre: "Programming",
    title: "Object Oriented Programming",
    published: "Dec 8, 2008",
    author: "John Smith",
    desc: "Object Oriented Programming using C#",
    img: "/images/book-10.jpg",
  },

  {
    id: 5,
    genre: "Nature",
    title: "Basics of Environmental Science",
    author: "Micheal Allaby",
    desc: "Three years have passed since the first edition of Basics of Environmental Science appeared. During this time new concerns have arisen, the controversy in Britain over the safety and desirability of genetically modified foods being the most spectacular example. At the same time, our understanding of other issues has improved as more information about them has been gathered.",
    published: "May 4, 2015",

    img: "/images/book-6.jpg",
  },
  {
    id: 6,
    genre: "Adventure",
    author: "Alexandre Dumas",
    title: "The count of Monte Cristo",
    published: "April 5, 2013",
    desc: "A classic adventure novel, often considered Dumas' best work, and frequently included on lists of the best novels of all time. Completed in 1844, and released as an 18-part series over the next two years, Dumas collaborated with other authors throughout. The story takes place in France, Italy, and the Mediterranean from the end of the rule of Napoleon I through the reign of Louis-Philippe.",
    img: "/images/book-7.jpg",
  },
  {
    id: 7,
    genre: "Language",
    title: "Language Learning",
    author: "Denyze Toffely",
    published: "July 23, 2005",
    desc: "It's the medium we use to communicate with others, think through our emotions, make decisions, and so much more. Once you've embraced a language so fully and consistently, is it possible to ever completely forget it? The short answer is yes, it is possible.",
    img: "/images/book-9.jpg",
  },
  {
    id: 8,
    genre: "Health",
    title: "Medicinal Herbs",
    author: "James A. Duke",
    desc: "Introduction By the time this second edition is published, the first edition of the Handbook of Medicinal Herbs will have been out more than 15 years. The second edition is designed to present most of the old information plus new information on the more important of those original 365 herbs",
    img: "/images/book-5.jpg",
    published: "Dec 7, 2013",
  },
  {
    id: 9,
    genre: "Mystery",
    title: "Tell me why",
    author: "Sandi Wallace",
    desc: "   Picturesque Daylesford has a darker side. Melbourne writer Georgie Harvey heads to the mineral springs region in central Victoria to look for a missing farmer, and soon links the woman�s disappearance with the unsolved mystery surrounding her husband. ",
    img: "/images/book-1.jpg",
    published: "27 June, 2010",
  },
  {
    id: 10,
    genre: "Fiction",
    title: "Displaced",
    author: "Stephen Drake",
    desc: "When Kevin Murdock, martial artist and outdoorsman extraordinaire, is revived from suspended animation aboard a transport pod, he and his nine fellow occupants have no idea what to expect.",
    published: "Jan 13, 2012",
    img: "/images/book-2.jpg",
  },
];
